# Build Docker container

name: Container Build

on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: 'Runner version'
        required: true
        default: '2.309.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        os:
        - ubuntu
        - debian
        - redhat-ubi8
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Container Metadata
        id: container_metadata
        run: |
          echo "container_name=${{ github.repository }}/${{ matrix.os }}-actions-runner" >> "$GITHUB_OUTPUT"
          echo "container_tag=${{ github.repository }}/${{ matrix.os }}-actions-runner:${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "datetime=$(date -Im)" >> "$GITHUB_OUTPUT"
      
      - name: Build Container
        run: |
          docker build -q -f ${{ matrix.os }}-actions-runner/Dockerfile \
            -t ghcr.io/${{ steps.container_metadata.outputs.container_tag }} \
            -t ghcr.io/${{ steps.container_metadata.outputs.container_name }}:latest \
            --build-arg COMMIT_SHA=${{ github.sha }} \
            --build-arg CREATED="${{ steps.container_metadata.outputs.datetime }}" \
            --build-arg GH_RUNNER_VERSION="${{ github.event.inputs.runner_version }}" \
            .
        shell: bash
      
      - name: Login GHCR.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish
        run: | 
          docker push -q -a ghcr.io/${{ steps.container_metadata.outputs.container_name }}
